export interface CountryType {
  code: string;
  label: string;
  phone: string;
  suggested?: boolean;
  phoneMask?: string;
}

export const countriesByCode: { [key: string]: CountryType } = {
  AD: { code: "AD", label: "Andorra", phone: "376", phoneMask: "3##-###" },
  AE: { code: "AE", label: "United Arab Emirates", phone: "971", phoneMask: "5#-###-####" },
  AF: { code: "AF", label: "Afghanistan", phone: "93", phoneMask: "7##-###-###" },
  AG: { code: "AG", label: "Antigua and Barbuda", phone: "1-268" },
  AI: { code: "AI", label: "Anguilla", phone: "1-264" },
  AL: { code: "AL", label: "Albania", phone: "355", phoneMask: "6#-###-####" },
  AM: { code: "AM", label: "Armenia", phone: "374", phoneMask: "##-###-###" },
  AO: { code: "AO", label: "Angola", phone: "244", phoneMask: "92#-###-###" },
  AQ: { code: "AQ", label: "Antarctica", phone: "672" },
  AR: { code: "AR", label: "Argentina", phone: "54", phoneMask: "##-####-####" },
  AS: { code: "AS", label: "American Samoa", phone: "1-684" },
  AT: { code: "AT", label: "Austria", phone: "43", phoneMask: "###-#######" },
  AU: { code: "AU", label: "Australia", phone: "61", suggested: true, phoneMask: "#-####-####" },
  AW: { code: "AW", label: "Aruba", phone: "297" },
  AX: { code: "AX", label: "Alland Islands", phone: "358" },
  AZ: { code: "AZ", label: "Azerbaijan", phone: "994", phoneMask: "##-###-##-##" },
  BA: { code: "BA", label: "Bosnia and Herzegovina", phone: "387", phoneMask: "6#-###-###" },
  BB: { code: "BB", label: "Barbados", phone: "1-246" },
  BD: { code: "BD", label: "Bangladesh", phone: "880", phoneMask: "1##-###-####" },
  BE: { code: "BE", label: "Belgium", phone: "32", phoneMask: "###-##-##-##" },
  BF: { code: "BF", label: "Burkina Faso", phone: "226", phoneMask: "##-##-##-##" },
  BG: { code: "BG", label: "Bulgaria", phone: "359", phoneMask: "###-###-###" },
  BH: { code: "BH", label: "Bahrain", phone: "973", phoneMask: "####-####" },
  BI: { code: "BI", label: "Burundi", phone: "257", phoneMask: "##-##-####" },
  BJ: { code: "BJ", label: "Benin", phone: "229", phoneMask: "##-##-##-##" },
  BL: { code: "BL", label: "Saint Barthelemy", phone: "590" },
  BM: { code: "BM", label: "Bermuda", phone: "1-441" },
  BN: { code: "BN", label: "Brunei Darussalam", phone: "673", phoneMask: "###-####" },
  BO: { code: "BO", label: "Bolivia", phone: "591", phoneMask: "7###-####" },
  BR: { code: "BR", label: "Brazil", phone: "55", phoneMask: "##-#####-####" },
  BS: { code: "BS", label: "Bahamas", phone: "1-242" },
  BT: { code: "BT", label: "Bhutan", phone: "975" },
  BV: { code: "BV", label: "Bouvet Island", phone: "47" },
  BW: { code: "BW", label: "Botswana", phone: "267", phoneMask: "7##-###-###" },
  BY: { code: "BY", label: "Belarus", phone: "375", phoneMask: "##-###-##-##" },
  BZ: { code: "BZ", label: "Belize", phone: "501" },
  CA: { code: "CA", label: "Canada", phone: "1", suggested: true, phoneMask: "###-###-####" },
  CC: { code: "CC", label: "Cocos (Keeling) Islands", phone: "61" },
  CD: { code: "CD", label: "Congo, Democratic Republic of the", phone: "243" },
  CF: { code: "CF", label: "Central African Republic", phone: "236", phoneMask: "7#-##-##-##" },
  CG: { code: "CG", label: "Congo, Republic of the", phone: "242", phoneMask: "##-###-####" },
  CH: { code: "CH", label: "Switzerland", phone: "41", phoneMask: "79 ###-####" },
  CI: { code: "CI", label: "Cote d'Ivoire", phone: "225", phoneMask: "##-###-###" },
  CK: { code: "CK", label: "Cook Islands", phone: "682" },
  CL: { code: "CL", label: "Chile", phone: "56", phoneMask: "#-####-####" },
  CM: { code: "CM", label: "Cameroon", phone: "237", phoneMask: "6##-##-##-##" },
  CN: { code: "CN", label: "China", phone: "86", phoneMask: "###-####-####" },
  CO: { code: "CO", label: "Colombia", phone: "57", phoneMask: "3##-###-####" },
  CR: { code: "CR", label: "Costa Rica", phone: "506", phoneMask: "####-####" },
  CU: { code: "CU", label: "Cuba", phone: "53", phoneMask: "5##-###-###" },
  CV: { code: "CV", label: "Cape Verde", phone: "238", phoneMask: "###-##-##" },
  CW: { code: "CW", label: "Curacao", phone: "599" },
  CX: { code: "CX", label: "Christmas Island", phone: "61" },
  CY: { code: "CY", label: "Cyprus", phone: "357", phoneMask: "9##-######" },
  CZ: { code: "CZ", label: "Czech Republic", phone: "420", phoneMask: "###-###-###" },
  DE: { code: "DE", label: "Germany", phone: "49", suggested: true, phoneMask: "1##-#######" },
  DJ: { code: "DJ", label: "Djibouti", phone: "253", phoneMask: "77 ##-##-##" },
  DK: { code: "DK", label: "Denmark", phone: "45", phoneMask: "##-##-##-##" },
  DM: { code: "DM", label: "Dominica", phone: "1-767" },
  DO: { code: "DO", label: "Dominican Republic", phone: "1-809", phoneMask: "###-###-####" },
  DZ: { code: "DZ", label: "Algeria", phone: "213", phoneMask: "###-##-##-##" },
  EC: { code: "EC", label: "Ecuador", phone: "593", phoneMask: "9##-###-###" },
  EE: { code: "EE", label: "Estonia", phone: "372", phoneMask: "5#######" },
  EG: { code: "EG", label: "Egypt", phone: "20", phoneMask: "1#-####-####" },
  EH: { code: "EH", label: "Western Sahara", phone: "212" },
  ER: { code: "ER", label: "Eritrea", phone: "291", phoneMask: "7#-###-###" },
  ES: { code: "ES", label: "Spain", phone: "34", phoneMask: "6##-###-###" },
  ET: { code: "ET", label: "Ethiopia", phone: "251", phoneMask: "9##-###-###" },
  FI: { code: "FI", label: "Finland", phone: "358", phoneMask: "4#-###-####" },
  FJ: { code: "FJ", label: "Fiji", phone: "679" },
  FK: { code: "FK", label: "Falkland Islands (Malvinas)", phone: "500" },
  FM: { code: "FM", label: "Micronesia, Federated States of", phone: "691" },
  FO: { code: "FO", label: "Faroe Islands", phone: "298" },
  FR: { code: "FR", label: "France", phone: "33", suggested: true, phoneMask: "#-##-##-##-##" },
  GA: { code: "GA", label: "Gabon", phone: "241", phoneMask: "#-##-##-##" },
  GB: { code: "GB", label: "United Kingdom", phone: "44", phoneMask: "7###-######" },
  GD: { code: "GD", label: "Grenada", phone: "1-473" },
  GE: { code: "GE", label: "Georgia", phone: "995", phoneMask: "5##-###-###" },
  GF: { code: "GF", label: "French Guiana", phone: "594" },
  GG: { code: "GG", label: "Guernsey", phone: "44" },
  GH: { code: "GH", label: "Ghana", phone: "233", phoneMask: "##-###-###" },
  GI: { code: "GI", label: "Gibraltar", phone: "350" },
  GL: { code: "GL", label: "Greenland", phone: "299" },
  GM: { code: "GM", label: "Gambia", phone: "220", phoneMask: "7##-##-##" },
  GN: { code: "GN", label: "Guinea", phone: "224", phoneMask: "6##-##-##-##" },
  GP: { code: "GP", label: "Guadeloupe", phone: "590" },
  GQ: { code: "GQ", label: "Equatorial Guinea", phone: "240", phoneMask: "222 ###-###" },
  GR: { code: "GR", label: "Greece", phone: "30", phoneMask: "69#-###-####" },
  GS: { code: "GS", label: "South Georgia and the South Sandwich Islands", phone: "500" },
  GT: { code: "GT", label: "Guatemala", phone: "502", phoneMask: "3#-##-##-##" },
  GU: { code: "GU", label: "Guam", phone: "1-671" },
  GW: { code: "GW", label: "Guinea-Bissau", phone: "245", phoneMask: "95#-###-###" },
  GY: { code: "GY", label: "Guyana", phone: "592", phoneMask: "6##-####" },
  HK: { code: "HK", label: "Hong Kong", phone: "852" },
  HM: { code: "HM", label: "Heard Island and McDonald Islands", phone: "672" },
  HN: { code: "HN", label: "Honduras", phone: "504", phoneMask: "9##-####" },
  HR: { code: "HR", label: "Croatia", phone: "385", phoneMask: "9#-###-####" },
  HT: { code: "HT", label: "Haiti", phone: "509", phoneMask: "3##-####" },
  HU: { code: "HU", label: "Hungary", phone: "36", phoneMask: "6-20-###-####" },
  ID: { code: "ID", label: "Indonesia", phone: "62", phoneMask: "8##-####-####" },
  IE: { code: "IE", label: "Ireland", phone: "353", phoneMask: "8#-###-####" },
  IL: { code: "IL", label: "Israel", phone: "972", phoneMask: "5#-###-####" },
  IM: { code: "IM", label: "Isle of Man", phone: "44" },
  IN: { code: "IN", label: "India", phone: "91", phoneMask: "#####-#####" },
  IO: { code: "IO", label: "British Indian Ocean Territory", phone: "246" },
  IQ: { code: "IQ", label: "Iraq", phone: "964", phoneMask: "7#-###-####" },
  IR: { code: "IR", label: "Iran, Islamic Republic of", phone: "98", phoneMask: "9##-###-####" },
  IS: { code: "IS", label: "Iceland", phone: "354", phoneMask: "###-####" },
  IT: { code: "IT", label: "Italy", phone: "39", phoneMask: "3##-###-####" },
  JE: { code: "JE", label: "Jersey", phone: "44" },
  JM: { code: "JM", label: "Jamaica", phone: "1-876", phoneMask: "###-###-####" },
  JO: { code: "JO", label: "Jordan", phone: "962", phoneMask: "7#-####-###" },
  JP: { code: "JP", label: "Japan", phone: "81", suggested: true, phoneMask: "##-####-####" },
  KE: { code: "KE", label: "Kenya", phone: "254", phoneMask: "7##-###-###" },
  KG: { code: "KG", label: "Kyrgyzstan", phone: "996", phoneMask: "##-###-###" },
  KH: { code: "KH", label: "Cambodia", phone: "855", phoneMask: "##-###-###" },
  KI: { code: "KI", label: "Kiribati", phone: "686" },
  KM: { code: "KM", label: "Comoros", phone: "269", phoneMask: "3##-##-##-##" },
  KN: { code: "KN", label: "Saint Kitts and Nevis", phone: "1-869" },
  KP: { code: "KP", label: "Korea, Democratic People's Republic of", phone: "850" },
  KR: { code: "KR", label: "Korea, Republic of", phone: "82", phoneMask: "1#-####-####" },
  KW: { code: "KW", label: "Kuwait", phone: "965", phoneMask: "5##-####" },
  KY: { code: "KY", label: "Cayman Islands", phone: "1-345" },
  KZ: { code: "KZ", label: "Kazakhstan", phone: "7", phoneMask: "7###-###-####" },
  LA: { code: "LA", label: "Lao People's Democratic Republic", phone: "856", phoneMask: "20##-###-###" },
  LB: { code: "LB", label: "Lebanon", phone: "961", phoneMask: "71 ###-###" },
  LC: { code: "LC", label: "Saint Lucia", phone: "1-758" },
  LI: { code: "LI", label: "Liechtenstein", phone: "423" },
  LK: { code: "LK", label: "Sri Lanka", phone: "94" },
  LR: { code: "LR", label: "Liberia", phone: "231", phoneMask: "886 ###-###" },
  LS: { code: "LS", label: "Lesotho", phone: "266", phoneMask: "58#-###-###" },
  LT: { code: "LT", label: "Lithuania", phone: "370", phoneMask: "6##-##-###" },
  LU: { code: "LU", label: "Luxembourg", phone: "352", phoneMask: "6##-###-###" },
  LV: { code: "LV", label: "Latvia", phone: "371", phoneMask: "2##-####" },
  LY: { code: "LY", label: "Libya", phone: "218", phoneMask: "##-###-####" },
  MA: { code: "MA", label: "Morocco", phone: "212", phoneMask: "6#-###-####" },
  MC: { code: "MC", label: "Monaco", phone: "377" },
  MD: { code: "MD", label: "Moldova, Republic of", phone: "373", phoneMask: "##-###-###" },
  ME: { code: "ME", label: "Montenegro", phone: "382", phoneMask: "6#-###-###" },
  MF: { code: "MF", label: "Saint Martin (French part)", phone: "590" },
  MG: { code: "MG", label: "Madagascar", phone: "261", phoneMask: "32 ##-###-##" },
  MH: { code: "MH", label: "Marshall Islands", phone: "692" },
  MK: { code: "MK", label: "Macedonia, the Former Yugoslav Republic of", phone: "389" },
  ML: { code: "ML", label: "Mali", phone: "223", phoneMask: "7#-##-##-##" },
  MM: { code: "MM", label: "Myanmar", phone: "95", phoneMask: "9##-###-###" },
  MN: { code: "MN", label: "Mongolia", phone: "976", phoneMask: "8##-####" },
  MO: { code: "MO", label: "Macao", phone: "853" },
  MP: { code: "MP", label: "Northern Mariana Islands", phone: "1-670" },
  MQ: { code: "MQ", label: "Martinique", phone: "596" },
  MR: { code: "MR", label: "Mauritania", phone: "222", phoneMask: "22##-####" },
  MS: { code: "MS", label: "Montserrat", phone: "1-664" },
  MT: { code: "MT", label: "Malta", phone: "356", phoneMask: "99##-####" },
  MU: { code: "MU", label: "Mauritius", phone: "230", phoneMask: "5###-####" },
  MV: { code: "MV", label: "Maldives", phone: "960", phoneMask: "7##-####" },
  MW: { code: "MW", label: "Malawi", phone: "265", phoneMask: "888 ##-####" },
  MX: { code: "MX", label: "Mexico", phone: "52", phoneMask: "##-####-####" },
  MY: { code: "MY", label: "Malaysia", phone: "60", phoneMask: "1#-###-####" },
  MZ: { code: "MZ", label: "Mozambique", phone: "258", phoneMask: "8#-##-##-###" },
  NA: { code: "NA", label: "Namibia", phone: "264", phoneMask: "8##-###-###" },
  NC: { code: "NC", label: "New Caledonia", phone: "687" },
  NE: { code: "NE", label: "Niger", phone: "227", phoneMask: "9#-##-##-##" },
  NF: { code: "NF", label: "Norfolk Island", phone: "672" },
  NG: { code: "NG", label: "Nigeria", phone: "234", phoneMask: "803 ###-####" },
  NI: { code: "NI", label: "Nicaragua", phone: "505", phoneMask: "8##-####" },
  NL: { code: "NL", label: "Netherlands", phone: "31", phoneMask: "6 ###-####" },
  NO: { code: "NO", label: "Norway", phone: "47", phoneMask: "4##-##-###" },
  NP: { code: "NP", label: "Nepal", phone: "977", phoneMask: "98#-###-####" },
  NR: { code: "NR", label: "Nauru", phone: "674" },
  NU: { code: "NU", label: "Niue", phone: "683" },
  NZ: { code: "NZ", label: "New Zealand", phone: "64", phoneMask: "2#-###-####" },
  OM: { code: "OM", label: "Oman", phone: "968", phoneMask: "9##-###-##" },
  PA: { code: "PA", label: "Panama", phone: "507", phoneMask: "6##-####" },
  PE: { code: "PE", label: "Peru", phone: "51", phoneMask: "9##-###-###" },
  PF: { code: "PF", label: "French Polynesia", phone: "689" },
  PG: { code: "PG", label: "Papua New Guinea", phone: "675", phoneMask: "7##-####" },
  PH: { code: "PH", label: "Philippines", phone: "63", phoneMask: "9##-###-####" },
  PK: { code: "PK", label: "Pakistan", phone: "92", phoneMask: "3##-#######" },
  PL: { code: "PL", label: "Poland", phone: "48", phoneMask: "6##-###-###" },
  PM: { code: "PM", label: "Saint Pierre and Miquelon", phone: "508" },
  PN: { code: "PN", label: "Pitcairn", phone: "870" },
  PR: { code: "PR", label: "Puerto Rico", phone: "1" },
  PS: { code: "PS", label: "Palestine, State of", phone: "970", phoneMask: "599 ###-###" },
  PT: { code: "PT", label: "Portugal", phone: "351", phoneMask: "9##-###-###" },
  PW: { code: "PW", label: "Palau", phone: "680" },
  PY: { code: "PY", label: "Paraguay", phone: "595", phoneMask: "9#-###-###" },
  QA: { code: "QA", label: "Qatar", phone: "974" },
  RE: { code: "RE", label: "Reunion", phone: "262" },
  RO: { code: "RO", label: "Romania", phone: "40", phoneMask: "7##-###-###" },
  RS: { code: "RS", label: "Serbia", phone: "381", phoneMask: "6#-###-###" },
  RU: { code: "RU", label: "Russian Federation", phone: "7", phoneMask: "9##-###-##-##" },
  RW: { code: "RW", label: "Rwanda", phone: "250", phoneMask: "78 ###-####" },
  SA: { code: "SA", label: "Saudi Arabia", phone: "966", phoneMask: "5#-###-####" },
  SB: { code: "SB", label: "Solomon Islands", phone: "677" },
  SC: { code: "SC", label: "Seychelles", phone: "248" },
  SD: { code: "SD", label: "Sudan", phone: "249" },
  SE: { code: "SE", label: "Sweden", phone: "46", phoneMask: "7#-###-##-##" },
  SG: { code: "SG", label: "Singapore", phone: "65", phoneMask: "8###-####" },
  SH: { code: "SH", label: "Saint Helena", phone: "290" },
  SI: { code: "SI", label: "Slovenia", phone: "386", phoneMask: "41 ###-###" },
  SJ: { code: "SJ", label: "Svalbard and Jan Mayen", phone: "47" },
  SK: { code: "SK", label: "Slovakia", phone: "421", phoneMask: "9##-###-###" },
  SL: { code: "SL", label: "Sierra Leone", phone: "232" },
  SM: { code: "SM", label: "San Marino", phone: "378" },
  SN: { code: "SN", label: "Senegal", phone: "221", phoneMask: "70#-###-####" },
  SO: { code: "SO", label: "Somalia", phone: "252", phoneMask: "252 ###-####" },
  SR: { code: "SR", label: "Suriname", phone: "597" },
  SS: { code: "SS", label: "South Sudan", phone: "211" },
  ST: { code: "ST", label: "Sao Tome and Principe", phone: "239" },
  SV: { code: "SV", label: "El Salvador", phone: "503", phoneMask: "7##-####" },
  SX: { code: "SX", label: "Sint Maarten (Dutch part)", phone: "1-721" },
  SY: { code: "SY", label: "Syrian Arab Republic", phone: "963" },
  SZ: { code: "SZ", label: "Swaziland", phone: "268" },
  TC: { code: "TC", label: "Turks and Caicos Islands", phone: "1-649" },
  TD: { code: "TD", label: "Chad", phone: "235", phoneMask: "6#-##-##-##" },
  TF: { code: "TF", label: "French Southern Territories", phone: "262" },
  TG: { code: "TG", label: "Togo", phone: "228" },
  TH: { code: "TH", label: "Thailand", phone: "66", phoneMask: "8#-###-####" },
  TJ: { code: "TJ", label: "Tajikistan", phone: "992", phoneMask: "92#-###-####" },
  TK: { code: "TK", label: "Tokelau", phone: "690" },
  TL: { code: "TL", label: "Timor-Leste", phone: "670" },
  TM: { code: "TM", label: "Turkmenistan", phone: "993" },
  TN: { code: "TN", label: "Tunisia", phone: "216", phoneMask: "2##-###-###" },
  TO: { code: "TO", label: "Tonga", phone: "676" },
  TR: { code: "TR", label: "Turkey", phone: "90", phoneMask: "5##-###-##-##" },
  TT: { code: "TT", label: "Trinidad and Tobago", phone: "1-868" },
  TV: { code: "TV", label: "Tuvalu", phone: "688" },
  TW: { code: "TW", label: "Taiwan", phone: "886" },
  TZ: { code: "TZ", label: "United Republic of Tanzania", phone: "255" },
  UA: { code: "UA", label: "Ukraine", phone: "380", phoneMask: "9#-###-##-##" },
  UG: { code: "UG", label: "Uganda", phone: "256", phoneMask: "7#-###-####" },
  US: { code: "US", label: "United States", phone: "1", suggested: true, phoneMask: "###-###-####" },
  UY: { code: "UY", label: "Uruguay", phone: "598" },
  UZ: { code: "UZ", label: "Uzbekistan", phone: "998" },
  VA: { code: "VA", label: "Holy See (Vatican City State)", phone: "379" },
  VC: { code: "VC", label: "Saint Vincent and the Grenadines", phone: "1-784" },
  VE: { code: "VE", label: "Venezuela", phone: "58" },
  VG: { code: "VG", label: "British Virgin Islands", phone: "1-284" },
  VI: { code: "VI", label: "US Virgin Islands", phone: "1-340" },
  VN: { code: "VN", label: "Vietnam", phone: "84", phoneMask: "9##-###-###" },
  VU: { code: "VU", label: "Vanuatu", phone: "678" },
  WF: { code: "WF", label: "Wallis and Futuna", phone: "681" },
  WS: { code: "WS", label: "Samoa", phone: "685" },
  XK: { code: "XK", label: "Kosovo", phone: "383" },
  YE: { code: "YE", label: "Yemen", phone: "967", phoneMask: "7##-###-###" },
  YT: { code: "YT", label: "Mayotte", phone: "262" },
  ZA: { code: "ZA", label: "South Africa", phone: "27", phoneMask: "7#-###-####" },
  ZM: { code: "ZM", label: "Zambia", phone: "260", phoneMask: "9##-###-###" },
  ZW: { code: "ZW", label: "Zimbabwe", phone: "263", phoneMask: "7#-###-####" },
};

export const countriesArray: CountryType[] = Object.values(countriesByCode);
